-- DML (Data Manupulation language) : 데이터를 조회(SELECT), 삭제(DELETE), 입력(INSERT), 변경(UPDATE)
-- 테이블이 아니고 데이터를 조작하는 것

-- DML을 하기 위해서 임시 테이블 생성
-- 기존 테이블을 복사
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

DROP TABLE DEPT_TEMP; -- 테이블을 삭제할 때 이용

-- 테이블에 데이터를 추가하기

INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(50, 'DATABASE','서울');
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(50, '부산', 'Development');
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES(70, '인천', NULL);

-- 2번째 방법
INSERT INTO DEPT_TEMP VALUES(80, '프론트',NULL);
INSERT INTO DEPT_TEMP(DEPTNO, DNAME) VALUES(90, '백엔드');

CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP
WHERE 1 != 1; -- 테이블을 복사해 새로운 테이블을 만들 때 데이터는 복사하지 않고 싶을 때 사용

SELECT * FROM EMP_TEMP;
DROP TABLE EMP_TEMP;

-- 테이블에 날짜 데이터 입력하기
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(9001, '나영석', 'PRESIDENT', NULL, SYSDATE, 2000, 1000, 10);

-- 서브쿼리를 이용한 INSERT
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
    FROM EMP E JOIN SALGRADE S
    ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    WHERE S.GRADE = 1;

-- UPDATE : 행의 정보를 변경할 때 사용
-- UPDATE 테이블이름 SET 변경할 열의 이름과 데이터 WEHRE 조건식
SELECT * FROM DEPT_TEMP2;

CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT_TEMP;

UPDATE DEPT_TEMP2
SET DNAME = '백엔드',
    LOC = '광주'
WHERE DEPTNO = 30;

CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

-- 조건절 없이 사용하면 모든 데이터 지워짐
DELETE FROM EMP_TEMP2
WHERE JOB = 'SALESMAN';


