-- 1.
SELECT EMPNO,
    RPAD(SUBSTR(EMPNO, 1, 2), 4, '*') AS MASKING_EMPNO,
    ENAME,
    RPAD(SUBSTR(ENAME,1,1), LENGTH(ENAME), '*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) = 5;

-- 2.
SELECT EMPNO, ENAME, SAL,
TRUNC(SAL / 21.5, 2) AS 일급,
ROUND(SAL / 21.5 / 8, 1) AS 시급
FROM EMP;

-- 3.
-- NEXT_DAY() : 기존 일자 다음에 오는 날짜
-- NVL(TO_CHAR(COMM),'N/A') 괄호 안의 값들이 같은 자료형이어야 함
SELECT EMPNO, ENAME, HIREDATE,
TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'MON'),'YYYY/MM/DD') AS R_JOB,
NVL(TO_CHAR(COMM),'N/A') AS COMM
FROM EMP;

SELECT EMPNO, ENAME, MGR,
    CASE
        WHEN MGR IS NULL THEN '0000'
        WHEN SUBSTR(MGR, 1, 2) = '75' THEN '5555'
        WHEN SUBSTR(MGR, 1, 2) = '76' THEN '6666'
        WHEN SUBSTR(MGR, 1, 2) = '77' THEN '7777'
        WHEN SUBSTR(MGR, 1, 2) = '78' THEN '8888'
        ELSE TO_CHAR(MGR)
    END AS CHG_MGR
FROM EMP;
        
-- 다중행 함수 : 여러 행에 대해 함수가 적용되어 하나의 결과를 나타내는 함수(집계 함수)
SELECT SUM(SAL)
FROM EMP;

SELECT SUM(SAL), ENAME
FROM EMP
GROUP BY ENAME;

-- GROUP BY : 그룹으로 묶을 때 사용
SELECT DEPTNO,
SUM(SAL), COUNT(*), ROUND(AVG(SAL),2), MAX(SAL), MIN(SAL)
FROM EMP
GROUP BY DEPTNO;

